#!/bin/bash

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NOCOLOR='\033[0m'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

function rust_diff {
    echo ""
    echo -e "${YELLOW}Verificando cambios en archivos de proyecto Rust...${NOCOLOR}"

    RUST_PATTERNS=("\.rs$" "\.toml$" "Cargo\.lock$")
    RUST_FILES_CHANGED=false

    for FILE in $STAGED_FILES; do
        for PATTERN in "${RUST_PATTERNS[@]}"; do
            if [[ $FILE =~ $PATTERN ]]; then
                echo -e "\t${RED}Archivo Rust modificado: ${FILE}${NOCOLOR}"
                RUST_FILES_CHANGED=true
                break
            fi
        done
    done

    if [ "$RUST_FILES_CHANGED" = true ]; then
        echo ""
        echo -e "${YELLOW}Se procede a ejecutar el script pre-commit:${NOCOLOR}"
        echo ""

        make pre-commit

        git add .
    else
        echo ""
        echo -e "${GREEN}No se detectaron cambios en archivos del proyecto Rust.${NOCOLOR}"
        echo ""
    fi
}

rust_diff

exit 0
